services:
  - type: web
    name: gamifikatsiya-backend
    runtime: python
    plan: free
    region: oregon
    rootDir: backend
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    buildCommand: bash ./build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
