# Generated by Django 4.2.11 on 2026-03-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('badge_earned', 'Badge olindi'), ('level_up', 'Level oshdi'), ('challenge_received', 'Challenge keldi'), ('challenge_result', 'Challenge natijasi'), ('tournament_start', 'Turnir boshlandi'), ('tournament_result', 'Turnir natijasi'), ('rank_changed', "Reyting o'zgardi"), ('streak_reminder', 'Streak eslatmasi'), ('quiz_result', 'Test natijasi'), ('daily_quest', 'Kunlik vazifa'), ('message', 'Xabar')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Push xatolari',
                'verbose_name_plural': 'Push xatolari',
                'db_table': 'notifications_pushlog',
            },
        ),
    ]
