# Generated by Django 4.2.11 on 2026-03-27 06:57

import apps.classroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=apps.classroom.models.generate_class_code, max_length=10, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('max_students', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinfxona',
                'verbose_name_plural': 'Sinfxonalar',
                'db_table': 'classroom_classroom',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=0)),
                ('use_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinfxona taklifi',
                'verbose_name_plural': 'Sinfxona takliflari',
                'db_table': 'classroom_invitation',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ro'yxatga olish",
                'verbose_name_plural': "Ro'yxatga olishlar",
                'db_table': 'classroom_enrollment',
                'ordering': ['-joined_at'],
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
