# Generated by Django 4.2.11 on 2026-03-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('xp_reward', models.IntegerField(default=10)),
                ('coin_reward', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classroom.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses_course',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('text', 'Matn'), ('video', 'Video'), ('interactive', 'Interaktiv')], default='text', max_length=20)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_duration_seconds', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=5)),
                ('coin_reward', models.IntegerField(default=2)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'db_table': 'courses_lesson',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dars progressi',
                'verbose_name_plural': 'Dars progresslari',
                'db_table': 'courses_lessonprogress',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp_earned', models.IntegerField(default=0)),
                ('coin_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurs yakunlash',
                'verbose_name_plural': 'Kurs yakunlashlar',
                'db_table': 'courses_coursecompletion',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
