# Generated by Django 4.2.11 on 2026-03-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('badge_type', models.CharField(choices=[('streak', 'Streak'), ('quiz', 'Test'), ('lesson', 'Dars'), ('social', 'Ijtimoiy'), ('special', 'Maxsus')], max_length=20)),
                ('condition_type', models.CharField(choices=[('count', 'Soni'), ('streak', 'Streak'), ('percentage', 'Foiz'), ('custom', 'Maxsus')], max_length=20)),
                ('condition_value', models.IntegerField(default=1)),
                ('xp_bonus', models.IntegerField(default=0)),
                ('coin_bonus', models.IntegerField(default=0)),
                ('rarity', models.CharField(choices=[('common', 'Oddiy'), ('rare', 'Kam uchraydigan'), ('epic', 'Epik'), ('legendary', 'Legendar')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'gamification_badge',
            },
        ),
        migrations.CreateModel(
            name='LevelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('min_xp', models.IntegerField()),
                ('max_xp', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='level_icons/')),
            ],
            options={
                'verbose_name': 'Level Unvoni',
                'verbose_name_plural': 'Level Unvonlari',
                'db_table': 'gamification_leveltitle',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('quiz_complete', 'Test yakunlandi'), ('lesson_complete', 'Dars yakunlandi'), ('badge_earn', 'Badge olindi'), ('streak_bonus', 'Streak bonus'), ('challenge_win', "Challenge g'alabasi"), ('challenge_lose', "Challenge mag'lubiyati"), ('daily_bonus', 'Kunlik bonus'), ('penalty', 'Jarima'), ('tournament_win', "Turnir g'alabasi"), ('referral', "Do'st taklifi")], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Tranzaksiya',
                'verbose_name_plural': 'XP Tranzaksiyalari',
                'db_table': 'gamification_xptransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_freeze_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
                'db_table': 'gamification_streak',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Badgesi',
                'verbose_name_plural': 'Foydalanuvchi Badgelari',
                'db_table': 'gamification_userbadge',
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('all_time', 'Umumiy')], default='weekly', max_length=20)),
                ('xp_points', models.IntegerField(default=0)),
                ('rank_position', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='classroom.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'db_table': 'gamification_leaderboardentry',
                'unique_together': {('student', 'classroom', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quest_type', models.CharField(choices=[('lesson', "Dars o'qish"), ('quiz', 'Test yechish'), ('social', "Do'stga challenge"), ('streak', 'Kunlik kirish')], max_length=20)),
                ('target_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik vazifa',
                'verbose_name_plural': 'Kunlik vazifalar',
                'db_table': 'gamification_dailyquest',
                'unique_together': {('student', 'quest_type', 'date')},
            },
        ),
    ]
