# Generated by Django 6.0.3 on 2026-03-28 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earned', 'Ishtirok'), ('spent', 'Sarflangan'), ('bonus', 'Bonus'), ('refund', 'Qaytarilgan')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('balance_after', models.IntegerField(default=0)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coin Tranzaksiya',
                'verbose_name_plural': 'Coin Tranzaksiyalari',
                'db_table': 'gamification_coin_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='coin_reward',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='transaction_type',
            field=models.CharField(choices=[('quiz_complete', 'Test yakunlandi'), ('lesson_complete', 'Dars yakunlandi'), ('badge_earn', 'Badge olindi'), ('streak_bonus', 'Streak bonus'), ('challenge_win', "Challenge g'alabasi"), ('challenge_lose', "Challenge mag'lubiyati"), ('daily_bonus', 'Kunlik bonus'), ('penalty', 'Jarima'), ('tournament_win', "Turnir g'alabasi"), ('referral', "Do'st taklifi"), ('quest_complete', 'Vazifa bajarildi'), ('daily_jackpot', 'Kunlik jackpot')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['student', 'date'], name='gamificatio_student_1c804b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['date', 'is_completed'], name='gamificatio_date_df9f90_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['student', '-created_at'], name='gamificatio_student_41627e_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='gamificatio_transac_61e866_idx'),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['student', '-created_at'], name='gamificatio_student_aab354_idx'),
        ),
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='gamificatio_transac_0313a1_idx'),
        ),
    ]
