# Generated by Django 6.0.3 on 2026-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_add_coin_reward_and_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='transaction_type',
            field=models.CharField(choices=[('quiz_complete', 'Test yakunlandi'), ('lesson_complete', 'Dars yakunlandi'), ('course_complete', 'Kurs yakunlandi'), ('badge_earn', 'Badge olindi'), ('streak_bonus', 'Streak bonus'), ('challenge_win', "Challenge g'alabasi"), ('challenge_lose', "Challenge mag'lubiyati"), ('daily_bonus', 'Kunlik bonus'), ('penalty', 'Jarima'), ('tournament_win', "Turnir g'alabasi"), ('referral', "Do'st taklifi"), ('quest_complete', 'Vazifa bajarildi'), ('daily_jackpot', 'Kunlik jackpot')], max_length=30),
        ),
    ]
