# Generated by Django 4.2.11 on 2026-03-27 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('in_progress', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('declined', 'Rad etilgan'), ('expired', "Muddati o'tgan")], default='pending', max_length=20)),
                ('challenger_score', models.FloatField(blank=True, null=True)),
                ('opponent_score', models.FloatField(blank=True, null=True)),
                ('xp_stake', models.IntegerField(default=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='classroom.classroom')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='quizzes.quiz')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'competition_challenge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tournament_type', models.CharField(choices=[('single_elimination', 'Yakkalik'), ('round_robin', 'Round Robin'), ('time_attack', 'Vaqtga intilish')], default='time_attack', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('max_participants', models.IntegerField(default=16)),
                ('status', models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('active', 'Faol'), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='upcoming', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('first_prize_xp', models.IntegerField(default=100)),
                ('second_prize_xp', models.IntegerField(default=50)),
                ('third_prize_xp', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='classroom.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_created', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'Turnir',
                'verbose_name_plural': 'Turnirlar',
                'db_table': 'competition_tournament',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.tournament')),
            ],
            options={
                'verbose_name': 'Turnir ishtirokchisi',
                'verbose_name_plural': 'Turnir ishtirokchilari',
                'db_table': 'competition_tournamentparticipant',
                'unique_together': {('tournament', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='competition.challenge')),
                ('quiz_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='quizzes.quizattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Urinish',
                'verbose_name_plural': 'Challenge Urinishlar',
                'db_table': 'competition_challengeattempt',
                'unique_together': {('challenge', 'student')},
            },
        ),
    ]
